# Generated by Django 3.2.7 on 2021-09-29 17:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('broker', models.CharField(max_length=50)),
                ('command_topic', models.CharField(max_length=50)),
                ('stat_topic', models.CharField(max_length=50)),
                ('payload', models.CharField(blank=True, max_length=100)),
                ('mac', models.CharField(max_length=50)),
                ('status', models.JSONField(max_length=500)),
            ],
        ),
    ]
