# Generated by Django 3.2.7 on 2021-09-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('broker', models.CharField(max_length=50)),
                ('command_topic', models.CharField(max_length=50)),
                ('stat_topic', models.CharField(max_length=50)),
                ('payload', models.CharField(blank=True, max_length=100)),
                ('mac', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=15)),
            ],
        ),
    ]
